# Generated by Django 3.2.9 on 2021-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerMsisdn', models.CharField(max_length=60)),
                ('totalAmount', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=60)),
                ('apiKey', models.CharField(max_length=60)),
            ],
        ),
    ]
