# Generated by Django 3.2.9 on 2021-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baipaga',
            name='appCode',
            field=models.CharField(default='', max_length=60),
        ),
    ]
