# Generated by Django 3.2.5 on 2021-12-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0002_baipaga_appcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MulticaixaExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60)),
                ('amount', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=60)),
                ('terminal', models.CharField(default='', max_length=60)),
                ('mobile', models.CharField(default='', max_length=60)),
                ('callbackUrl', models.CharField(default='', max_length=60)),
                ('card', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
