# Generated by Django 3.2 on 2022-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0004_multicaixaexpress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='multicaixaexpress',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
    ]
