# Generated by Django 3.2 on 2022-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0006_alter_multicaixaexpress_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='multicaixaexpress',
            name='tokenApp',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='multicaixaexpress',
            name='token',
            field=models.CharField(max_length=60),
        ),
    ]
