# Generated by Django 3.2 on 2022-03-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0008_auto_20220321_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='baipaga',
            name='reference',
            field=models.CharField(default='', max_length=60),
        ),
    ]
