# Generated by Django 3.2 on 2022-03-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0009_baipaga_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baipaga',
            name='reference',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='multicaixaexpress',
            name='reference',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
