# Generated by Django 3.2 on 2022-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentosapp', '0013_references_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='valueUSD',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
